/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertNotNull;

import java100.app.App;

public class AppTest {
     public void testAppHasAGreeting() {
        App classUnderTest = new App();
    //    assertNotNull("app should have a greeting", classUnderTest.getGreeting());

    }
}
